### PR TITLE
UI/UX

### PR DESCRIPTION
**Pull request by hmc-cs-hching**
Updating UI/UX. Added login page and actionListener for login button. Reformatted conversation and message panels

### CODE REVIEW

**Comment by evansenter** [comment]
Please remove all the .class files, generated code generally doesn't go in the repo. :D

**Comment by evansenter** [comment]
Actually, and the .idea folder and everything under bin as well. Should probably update the .gitignore to ignore everything in bin and .idea

**Comment by evansenter** [comment]
Also, some of these changes look identical to Jasper's stuff--ie. Password.java, is this a PR that's dependent on his PR going in first?

**Comment by hmc-cs-hching** [comment]
I pulled his branch into my branch because I needed the login code for the action event listener button. so i think we dont need his pull request because all his changes are in my pull request. sorry for making that confusing.

**Comment by evansenter** [comment]
The problem with that is any changes on that PR before it goes in won't get captured over here, without manually cherry-picking those commits over. I'm actually not really sure what the best way to do something like this is on Github, probably branch of their branch and then make changes from there, and point it back at master once the upstream PR (that has the changes you need) is pushed in.

At any rate, you'll still want to remove all the .class files, anything under bin/ and .idea/ before this is ready to go, and it should wait for #4 before going in. Hard for me to review it with all the other stuff in it at the moment. :smile:

**Pull request merged**
